# Generated by Django 2.2 on 2019-04-28 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lab',
            options={'verbose_name_plural': 'Labs'},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name_plural': 'Todos'},
        ),
    ]
